### ISSUE TITLE
[Server] [App] Delegate orientation commands to current operator

### ISSUE THREAD

**Issue by trylimits** [Blackjack92/fhvRobot#119]
The received orientation commands as described in #114 are correctly handled by the server, however, this data has to be delegated to the current operator of the robot.

We have to implement a `Delegator` which re-sends these commands to the current app operator with as low latency as possible.

**Comment by Blackjack92** [comment]
I think we have two possibilities
* use the already implemented `CommunicationDelegator` and display the compass control in each app client
* implement an `OperatorDelegator` which does only forward the messages to the current operator

I think if the latency is not too high we can use the existing `CommunicationDelegator`, because I would show the compass on each app (also non operators).
