### ISSUE TITLE
[App] Message when connection not possible

### ISSUE THREAD

**Issue by Blackjack92** [Blackjack92/fhvRobot#47]
Display connection not possible when WLAN is off or no answer to the send open command.

**Comment by trylimits** [comment]
This was already introduced in #31 

The behavior is as follows:

After starting the game the `CommunicationClient` tries to establish a connection. The progress of connection establishment is shown to the user (session created, registered, ...). If no connection can be established (either because of down server or no internet connection) the connection establishment fails safely and reports this to the user. The app switches then back to the "login screen".
